# Лабораторная работа 6.

## Задание 1

In [13]:
import numpy as np

a1 = np.random.randint(0, 10, size=(3, 3))
a2 = np.random.randint(0, 10, size=(3, 3))

h1 = np.hstack((a1, a2))
print(h1, end = "\n\n")

v1 = np.vstack((a1, a2))
print(v1, end = "\n\n")

[[6 8 4 7 9 9]
 [1 4 9 3 6 7]
 [8 1 1 2 0 3]]

[[6 8 4]
 [1 4 9]
 [8 1 1]
 [7 9 9]
 [3 6 7]
 [2 0 3]]



## Задание 2

In [16]:
import numpy as np

# Generate a 5x5 matrix using np.random.rand
a = np.random.randint(0, 10, size=(5, 5))

print(a,end = '\n\n')

# Remove the first two rows
a = np.delete(a, [0, 1], axis=0)

# Remove the last column
a = np.delete(a, -1, axis=1)

print(a)

[[4 6 8 2 3]
 [0 0 6 0 6]
 [3 3 8 8 8]
 [2 3 2 0 8]
 [8 3 8 2 8]]

[[3 3 8 8]
 [2 3 2 0]
 [8 3 8 2]]


## Задание 3

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
main_diagonal = a.diagonal()
print(main_diagonal)  # [1, 5, 9]

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
side_diagonal = np.fliplr(a).diagonal()
print(side_diagonal)  # [3, 5, 7]

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
plus_one_diagonal = a.diagonal(offset=1)
print(plus_one_diagonal)  # [2, 6]

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
minus_one_diagonal = a.diagonal(offset=-1)
print(minus_one_diagonal)  # [4, 8]

[1 5 9]
[3 5 7]
[2 6]
[4 8]


## Задание 4

In [19]:
import numpy as np

n = 8
matrix = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        if (i + j) % 2 == 0:
            matrix[i, j] = 1
        else:
            matrix[i, j] = 0

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## Задание 5

In [22]:
import numpy as np

# Создаем матрицу 3-го порядка, заполненную случайными числами
A = np.random.randint(0, 10, size = (3,3))

# Создаем диагональную матрицу
D = np.diag(A.diagonal())

print(D)

[[8 0 0]
 [0 9 0]
 [0 0 1]]


In [25]:
import numpy as np

# Создаем матрицу 3-го порядка, заполненную случайными числами
A = np.random.randint(0, 10, size = (3,3))

# Создаем побочную диагональ
side_diagonal = np.fliplr(A).diagonal()

# Создаем диагональную матрицу
D = np.diag(side_diagonal)

print(D)

[[6 0 0]
 [0 7 0]
 [0 0 8]]


In [31]:
import numpy as np

# Создаем матрицу 3-го порядка, заполненную случайными числами
A = np.random.randint(0, 10, size = (9,9))

# Создаем плоский список из элементов матрицы
flat_list = A.flatten()

# Создаем диагональную матрицу
D = np.diag(flat_list)

print(D)

[[1 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 4 0 0]
 [0 0 0 ... 0 4 0]
 [0 0 0 ... 0 0 4]]


In [30]:
import numpy as np

# Создаем матрицу 3-го порядка, заполненную случайными числами
A = np.random.randint(0, 10, size = (9,9))

# Создаем плоский список из элементов матрицы
flat_list = A.flatten()

# Создаем матрицу 9-го порядка
D = np.zeros((9, 9))

# Заполняем побочную диагональ
for i in range(9):
    D[i, 8-i] = flat_list[i]

print(D)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Задание 6

In [33]:
# 54x - 2y + 3z = -35
# 4x + 2y + 17z = 27
# 3x + 2y + 74z = 19

import numpy as np

A = np.array([[54, -2, 3], [4, 2, 17], [3, 2, 74]])
b = np.array([-35, 27, 19])

x = np.linalg.solve(A, b)

print(x)

[-0.08899579 14.88424534 -0.14191221]


## Задание 7

In [34]:
import numpy as np

A = np.array([[54, -2, 3], [4, 2, 17], [3, 2, 74]])
b = np.array([-35, 27, 19])

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)

print(x)

[-0.08899579 14.88424534 -0.14191221]


## Задание 8

Функция np.linalg.solve(a, b) и матричный метод дают один и тот же результат, что подтверждает корректность реализации этих методов в библиотеке NumPy.

Оба метода могут быть использованы для решения СЛАУ, но функция np.linalg.solve(a, b) является более простой и эффективной, так как она автоматически выбирает оптимальный алгоритм для решения системы.

## Задание 9

In [45]:
import numpy as np
from scipy.optimize import fsolve

def g(x):
    return x**4 - 6*x**3 + 4*x**2 + 10*x + 75

root = fsolve(g, 1)  # начальное значение x=1
print("Корень уравнения:", root)

Корень уравнения: [-0.5339629]


C:\Users\s-pod\AppData\Local\Temp\ipykernel_6456\2121196835.py:7: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  root = fsolve(g, 1)  # начальное значение x=1


## Задание 10

In [42]:
import numpy as np
from scipy.optimize import root

def func(xy):
    x, y = xy
    if np.abs(y) < 1e-6:  # Избегаем деление на 0
        return [np.inf, np.inf]
    return [x**2 - y**3 + (x/np.sin(y) + 2) + 2**x - 15,
            x*np.cos(y)**2 + np.exp(x-y) - y**2 - 17]

x0 = [1, 1]
result = root(func, x0, method='lm')
print("Корень системы уравнений:", result.x)

Корень системы уравнений: [2.54404027 0.42769733]
